---
- import_tasks: preflight.yml
  become: true

- import_tasks: install.yml
  become: true

- import_tasks: configure.yml
  become: true

- name: Ensure Traefik service is started
  become: true
  systemd:
    name: traefik
    daemon_reload: true
    state: started
  tags:
    - traefik_run
